version: 2

project_name: gridctl

before:
  hooks:
    # Build frontend before Go compilation
    - npm ci --prefix web
    - npm run build --prefix web
    - mkdir -p cmd/gridctl/web
    - cp -r web/dist cmd/gridctl/web/

builds:
  - id: gridctl
    main: ./cmd/gridctl
    binary: gridctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=embed_web
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^style:"
      - "^ci:"
      - "^build:"
  groups:
    - title: Breaking Changes
      regexp: '^.*!:'
      order: 0
    - title: Features
      regexp: "^feat"
      order: 1
    - title: Bug Fixes
      regexp: "^fix"
      order: 2
    - title: Performance
      regexp: "^perf"
      order: 3
    - title: Refactoring
      regexp: "^refactor"
      order: 4
    - title: Others
      order: 999

release:
  github:
    owner: gridctl
    name: gridctl
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  header: |
    ## What's New in {{ .Tag }}

    See the [CHANGELOG](https://github.com/gridctl/gridctl/blob/main/CHANGELOG.md) for full release history.

    ---
  footer: |
    ---
    ## Installation

    **Homebrew (macOS)**:
    ```bash
    brew install gridctl/tap/gridctl
    ```

    **Binary Download**: See assets below for your platform.

    **Full Changelog**: https://github.com/gridctl/gridctl/compare/{{ .PreviousTag }}...{{ .Tag }}

homebrew_casks:
  - name: gridctl
    repository:
      owner: gridctl
      name: homebrew-tap
      token: "{{ .Env.GORELEASER_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/gridctl/gridctl"
    description: "MCP orchestration tool - Containerlab for AI Agents"
    binaries:
      - gridctl
    hooks:
      post:
        install: |
          system_command "/usr/bin/xattr",
                         args: ["-dr", "com.apple.quarantine", "#{staged_path}/gridctl"]
